version: '3.8'

services:
  dashdot:
    image: mauricenino/dashdot:latest
    container_name: dashdot
    restart: unless-stopped
    privileged: true
    ports:
      - 3001:3000
    volumes:
      - /etc/os-release:/host/etc/os-release:ro
      - /proc:/host/proc:ro
      - /:/mnt/host:ro

  app:
    build: .
    container_name: personal_website_app
    ports:
      - "3000:3000"
    volumes:
      - uploads_profiles:/app/public/uploads/profiles
      - uploads_sensitive:/app/public/uploads/sensitive
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: carricinha
      DB_NAME: meu-site
      SESSION_SECRET: david-secret-key
    depends_on:
      - db
    restart: always

  db:
    image: mysql:8.0
    container_name: site_mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: carricinha
      MYSQL_DATABASE: meu-site
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

volumes:
  db_data:
  uploads_profiles:
  uploads_sensitive:
